import type { GameSettings } from '../entities/server-configs/model/types.js'

const base: GameSettings = {
  playerHealthFactor: 1.0,
  playerManaFactor: 1.0,
  playerStaminaFactor: 1.0,
  playerBodyHeatFactor: 1.0,
  enableDurability: 1.0,
  enableStarvingDebuff: 1.0,
  foodBuffDurationFactor: 1.0,
  fromHungerToStarving: 600000000000,
  shroudTimeFactor: 1.0,
  tombstoneMode: 0,
  miningDamageFactor: 1.0,
  plantGrowthSpeedFactor: 1.0,
  resourceDropStackAmountFactor: 1.0,
  factoryProductionSpeedFactor: 1.0,
  perkUpgradeRecyclingFactor: 0.5,
  perkCostFactor: 1.0,
  experienceCombatFactor: 1.0,
  experienceMiningFactor: 1.0,
  experienceExplorationQuestsFactor: 1.0,
  aggroPoolAmount: 1.0,
  enemyDamageFactor: 1.0,
  enemyHealthFactor: 1.0,
  enemyStaminaFactor: 1.0,
  enemyPerceptionRangeFactor: 1.0,
  bossDamageFactor: 1.0,
  bossHealthFactor: 1.0,
  threatBonusFactor: 1.0,
  pacifiedEnemies: 0,
  dayTimeDuration: 1800000000000,
  nightTimeDuration: 720000000000,
  waterOfTheWakeMode: 0,
  waterOfTheWakeDistance: 100
}

export const presets: Record<string, GameSettings> = {
  Default: { ...base },
  Relaxed: {
    ...base,
    playerHealthFactor: 2.0,
    playerManaFactor: 2.0,
    playerStaminaFactor: 2.0,
    enableDurability: 0,
    enableStarvingDebuff: 0,
    foodBuffDurationFactor: 2.0,
    shroudTimeFactor: 2.0,
    miningDamageFactor: 2.0,
    plantGrowthSpeedFactor: 2.0,
    resourceDropStackAmountFactor: 2.0,
    factoryProductionSpeedFactor: 2.0,
    experienceCombatFactor: 2.0,
    experienceMiningFactor: 2.0,
    experienceExplorationQuestsFactor: 2.0,
    enemyDamageFactor: 0.5,
    enemyHealthFactor: 0.5,
    enemyStaminaFactor: 0.5,
    bossDamageFactor: 0.5,
    bossHealthFactor: 0.5,
    tombstoneMode: 0
  },
  Hard: {
    ...base,
    playerHealthFactor: 0.5,
    playerManaFactor: 0.5,
    playerStaminaFactor: 0.5,
    enableDurability: 1.0,
    enableStarvingDebuff: 1.0,
    foodBuffDurationFactor: 0.5,
    shroudTimeFactor: 0.5,
    miningDamageFactor: 0.5,
    resourceDropStackAmountFactor: 0.5,
    experienceCombatFactor: 0.5,
    experienceMiningFactor: 0.5,
    experienceExplorationQuestsFactor: 0.5,
    enemyDamageFactor: 2.0,
    enemyHealthFactor: 2.0,
    enemyStaminaFactor: 2.0,
    enemyPerceptionRangeFactor: 2.0,
    bossDamageFactor: 2.0,
    bossHealthFactor: 2.0,
    threatBonusFactor: 2.0,
    tombstoneMode: 1
  },
  Survival: {
    ...base,
    playerHealthFactor: 0.25,
    playerManaFactor: 0.25,
    playerStaminaFactor: 0.25,
    enableDurability: 1.0,
    enableStarvingDebuff: 1.0,
    foodBuffDurationFactor: 0.25,
    shroudTimeFactor: 0.25,
    fromHungerToStarving: 300000000000,
    miningDamageFactor: 0.5,
    resourceDropStackAmountFactor: 0.25,
    factoryProductionSpeedFactor: 0.5,
    experienceCombatFactor: 0.25,
    experienceMiningFactor: 0.25,
    experienceExplorationQuestsFactor: 0.25,
    enemyDamageFactor: 4.0,
    enemyHealthFactor: 4.0,
    enemyStaminaFactor: 4.0,
    enemyPerceptionRangeFactor: 4.0,
    bossDamageFactor: 4.0,
    bossHealthFactor: 4.0,
    threatBonusFactor: 4.0,
    tombstoneMode: 2,
    pacifiedEnemies: 0
  }
}
